name: Checkout repository
description: Checkout repository with patches to avoid running out of disk space
runs:
  using: 'composite'
  steps:
    - name: Maximize build space
      if: ${{ runner.os == 'Linux' }}
      uses: easimon/maximize-build-space@master
      with:
        swap-size-mb: 3072
        root-reserve-mb: 3072
        remove-dotnet: 'true'
        remove-codeql: 'true'
        remove-haskell: 'true'
        remove-docker-images: 'true'

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Symlink target to C:\
      if: ${{ runner.os == 'Windows' }}
      shell: powershell
      run: |
        New-Item -ItemType Directory -Force -Path C:\spacedrive_target
        New-Item -Path target -ItemType Junction -Value C:\spacedrive_target
