[package]
name = "sd-media-data"
version = "0.0.0"
authors = ["Jake Robinson <jake@spacedrive.com>"]
edition = "2021"

[dependencies]
kamadak-exif = "0.5.5"
thiserror = "1.0.43"
image-rs = { package = "image", version = '0.24.6' }
sd-prisma = { path = "../prisma" }
serde = { version = "^1.0", features = ["derive"] }
serde_json = { version = "^1.0" }
specta = { workspace = true }
chrono = { version = "0.4.26", features = ["serde"] }
tokio = { workspace = true, features = ["rt"] }
