[package]
name = "sd-media-data"
version = "0.0.0"
authors = ["Jake Robinson <jake@spacedrive.com>"]
edition = "2021"

[features]
default = ["zeroize", "serde"]
zeroize = [
	"dep:zeroize",
] # this is used to enable zeroize traits such as `DefaultIsZeroes`
serde = ["dep:serde", "dep:serde_json"]

[dependencies]
kamadak-exif = "0.5.5"
thiserror = "1.0.43"

zeroize = { version = "^1.6", optional = true }
sd-prisma = { path = "../prisma" }
serde = { version = "^1.0", features = ["derive"], optional = true }
serde_json = { version = "^1.0", optional = true }

chrono = { version = "0.4.26", features = ["serde"] }
[dev-dependencies]
walkdir = "2.3.3"
rand = "0.8.5"
